version: '3.8'
services:
  postgres-product:
    container_name: postgres-product
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-product-data:/var/lib/postgresql/data

volumes:
  postgres-product-data: 